pipeline {
    agent any
    stages{
          stage('Fetch') {
            steps {
               sh 'echo $JOB_NAME'
                sh 'echo $BUILD_NUMBER'
                sh 'echo Fetch'
               git branch: 'master', url: 'https://github.com/roshenreji/PassportApp.git'
            }
        }
        
        stage('Path'){
            steps{
                sh 'echo Path'
                sh 'pwd && ls'
            }
        }
        stage('Clean'){
            steps{
                dir("C:/Users/roshe/.jenkins/workspace/JenkinChallenge/PassportApplication"){
                    sh 'echo Clean'
                    sh 'mvn  clean'
                }
            }
        }
        stage('Validate'){
                steps{
                     dir("C:/Users/roshe/.jenkins/workspace/JenkinChallenge/PassportApplication"){
                
                        sh 'mvn  validate'
                     }
                }
            
         }
        stage('Compile'){
                steps{
                     dir("C:/Users/roshe/.jenkins/workspace/JenkinChallenge/PassportApplication"){
                        sh 'echo Compile'
                         sh 'mvn  compile'
                     }
                }
            
        }
        stage('Sonar Analysis'){
            steps{
                 dir("C:/Users/roshe/.jenkins/workspace/JenkinChallenge/PassportApplication"){
                    withSonarQubeEnv('SonarCloud'){
                    sh 'mvn sonar:sonar'
                  }
            }
            }
            
        }
        stage('Build'){
            steps {
                 dir("C:/Users/roshe/.jenkins/workspace/JenkinChallenge/PassportApplication"){
                
                        sh 'echo Build'
                        sh 'mvn  package'
                 }
            }
            
            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'PassportApplication/target/*.jar'
                     }
                }
             }
             stage('Test'){
                 steps {
                      dir("C:/Users/roshe/.jenkins/workspace/JenkinChallenge/PassportApplication"){
                         sh 'echo Test'
                         sh 'mvn test'
                      }
                 }
            }
        
    }
}
